L = [10,20,30,40,50,60,70,80];
print("Original list is",L);
L.append(200);
L.append(300);
print("List after appending elements is",L);
L.remove(10);
L.remove(30);
print("List after removing elements is",L);
L.sort();
print("List after sorting in ascending order is",L);
L.sort(reverse = "True");
print("List after sorting in descending order is",L);