import numpy as np;
import matplotlib.pyplot as plt;
import seaborn as sns;
roll_number = 1;
np.random.seed(roll_number);
df = np.random.randn(50);
fig,ax = plt.subplots(2,2,figsize = (10,8));
ax[0][0].plot(df,np.cumsum(df),label = "Cumulative Sum",color = "red");
ax[0][0].set_title('Cumulative Sum');
ax[0][0].set_xlabel('Index');
ax[0][0].set_ylabel('Cumulative Sum');
ax[0][0].grid(True);
ax[0][1].scatter(np.arange(len(df)),df,label = "Random Noise",color = "green");
ax[0][1].set_title('Random Noise');
ax[0][1].set_xlabel('Index');
ax[0][1].set_ylabel('Random Noise');
ax[0][1].grid(True);
plt.tight_layout();
plt.show();